#!/usr/bin/env sh

version() {
    echo "reviewer git plugin v0.0.1"
    echo
}

usage() {
    echo "usage: git reviewer [ref]"
    echo
}

get_changes() {
	local ref=$1
	local changes=$(git diff --name-only $ref)

	if [ -z "${changes// }" ]; then
		# no changes, go back one commit
		ref="$1~1"
		changes=$(get_changes $ref)
	fi

	echo "$changes"
}

main() {
	case "$1" in
		-v)        version; exit;;
		--version) version; exit;;
		-h)        usage; exit;;
		--help)    usage; exit;;
	esac

	# check if repo has commits
	git rev-parse HEAD > /dev/null 2>&1
	if [ $? != 0 ]; then
	    echo 'No commits to examine.'
	    exit
	fi

	ref=$1
	if [ -z $ref ]; then
		ref="HEAD"
	fi
	
	changes=$(get_changes $ref)
	changes=$(
		echo "$changes" | \
		xargs -n1 -I % git blame -e % $ref 2> /dev/null | \
		sed "s/^[^(]*(<\([^\>]*\)>.*$/\1/p" | \
		sort | uniq -c | sort -nr
	)
	
	total_lines=$(
		echo "$changes" | \
		awk '{ SUM += $1} END { print SUM }'
	)

	if [ $total_lines -eq 0 ]; then
	    echo "Only new files have been added, unable to determine a reviewer."
	else
	    echo "Top 3 authors of the files that have been changed:"
	    echo "$changes" | \
		awk -v total="$total_lines" '{sum = $1 / total * 100; printf "%4d%s %s\n", int(sum), "%", $2}' | \
		head -n 3
	fi
}

main "$@"
